define love = Character("Love")
define jacobs = Character("Jacobs")
define kid = Character("kid", color="#c3a38a")
define gray = Character("Grayson", color="#c3a38a")
define max = Character("Max", color="#c3a38a")
define patty = Character("Mrs. Patricia", color="#c3a38a")

label start:
    # Show a background. This uses a placeholder by default, but you can
    # add a file (named either "bg room.png" or "bg room.jpg") to the
    # images directory to show it.

    scene bg room

    # This shows a character sprite. A placeholder is used, but you can
    # replace it by adding a file named "eileen happy.png" to the images
    # directory.

    #show eileen happy

    "You wake up to the sound of someone yelling and banging what sounds like a frying pan"
    
    "Cook" "Everyone, up up up! Get up!"
    jacobs "Love, get up. We've finally got them!"
    
    "You get out of bed and head to the command center"
    love "Let's get them!"

    "After a fierce chase, they get hit, but manage to get away"
    jacobs "Let's dock, we'll try again tomorrow"
    love "Alright..."
    
    "You land on the planet"
    "You buy some local suevineers, when you realize you forgot your coat back at the restraunt"
    love "I'll meet you back at the base"
    jacobs "Be back in time for dinner"
    
    love "Wow, it sure is crowded at night"
    "You bump into someone"
    "Thug" "Hey, watch where you're going."
    love "Sorry"
    "Thug2" "Yeah miss, you gotta keep your eyes open"
    "A third thug butts in"
    "Thug3" "Hey, you ain't from around here, are's ya?"
    "Scared, you back up. But the thugs keep getting closer, invading your space"
    love "Hey, umm... I'm sorry"
    "Thug1" "Sorry ain't gunna cut it"
    "You look around, and realize you're in an alley way"
    "Thug2" "Tsk tsk, ain't nowhere to run sweety"
    
    kid "Hey, there some sort of a problem here?"
    "Thug3" "Keep walking, kid?"
    "The thugs turn back to you"
    "Thug3" "Ow! What the..."
    "The kid had thrown a rock at the thug"
    
    "Thug2 pulls out a knife"
    "Thug1" "Hey brat, you really hurt my friend"
    "Thug2 manages to grab the kid"
    "Thug2" "You gotta learn some manners kid... And I got some learning you won't forgot..."
    "Thug3" "Cut his ear off! That'll show the punk!"
    "The kid begins to cry"
    
    max "Let go of my brother!"
    "Max comes in, swinging, knocking out the thug with the knife, and kicking it away"
    max "Grayson, go get help! Hurry!"
    "The kid nods, wiping away his tears, and runs off"
    
    "Thug1" "You got a lot of nerve kid..."
    "You take your chance"
    love "Hiya!"
    "You kick the third thug in the shin, and sock him in the face, he falls down"
    "Thug 3" "Auauauaughhghh... What the hell?"
    "Distracted, Max sucker punches the first thug"
    max "C'mon!"
    
    "You run past the thugs, Max grabs your hand, and the two of you run into the crowd"
    
    "You find Grayson talking to some confused men in business suits"
    max "Grayson! There you are!"
    gray "Brother! I found help"
    "Businessman" "Like I said, I don't think we're equipped to help, you really should find a..."
    
    max "No problem, sir. Sorry to bother you, but we've got it covered now. Thank you so much for your time."
    "The businessman, confused, shrugs and walks off"
    "Max looks to you"
    max "You should head home, you've had a rough time. Where do you live?"
    love "Not far... But, it's fine, I can-"
    gray "Hey, don't I get some sort of reward???"
    max "Grayson!"
    "You laugh"
    max "In fact you do, you get to walk the lady home."
    gray "awww..."
    "Everyone laughs"
    
    "You tell Jacobs about the event, and go straight to bed"
    love "What was his name again? Max?"
    "You spend the next few uneventful days in space, no bandit attacks."
    
    love "Maybe they got away?"
    jacobs "It's possible, but not likely"
    
    love "Why not"
    jacobs "For an unassisted trans-planetary departure, they'd need some serious hardware."
    love "Hmm... What stops them from just mimicking another ship?"
    jacobs "Nothing really, but the planetary egress logs would have duplicate departures and no re-entries..."
    love "I see..."
    jacobs "Wait... but... What if we did an in-flight scan... and..."
    "Jacobs begins to mumble to himself as he tabs the computer screen"
    jacobs "We found him!"
    love "What?"
    
    "You and your crew approach, but the ship fires first and runs. Another persuit."
    "While flying, a cargo ship gets stuck in the crossfire, and is destroyed."
    "This gives the bandits a chance to escape, as you search for survivors"
    "There are none"
    
    jacobs "We'll keep looking for duplicate signatures, you need some time off"
    
    "You return back to the planet to take a day of vacation."
    
    love "I was hoping we'd cross paths again, but..."
    "You spot a child with his nose pressed on a toystore window"
    love "Grayson? Grayson is that you!"
    "You run over, but... no. It's just some random kid."
    love "Sorry"
    
    "Your brief day-long vacation is over, and you head back to the ship"
    "As soon as you arrive, Jacobs flags you down"
    jacobs "We've got him. They're cycling their signatures now, using docked ships to avoid duplication"
    love "How do we know?"
    jacobs "Log Deltas. I've..."
    "You don't understand any of the techno-mumbo-jumbo he's saying"
    love "... right. Yes. Good. Checks out"
    
    "The Cook butts into your conversation"
    "Cook" "What's wrong Love? You not eating so well lately"
    love "Hmm? What do you mean?"
    "Jacobs stands up from in front of the computer, and shouts!"
    jacobs "It's them!"
    
    "You all gather in the command center"
    love "This is our last chance. Innocents were killed last time." 
    love "We can't let this keep going on."
    jacobs "The ship looks a little different... Some sort of upgrade or modification?"
    jacobs "We should be more cautious, we don't know what they have outfitted."
    
    love "Can we get a closer look?"
    jacobs "Sure"
    jacobs "..."
    jacobs "aaaand we've been spotted."
    
    "A pursuit ensues"
    love "Pilot"
    "Pilot" "Yes mam?"
    love "Keep an extra eye out for civilians. Make sure none come between us. I..."
    love "I don't want a repeat of last time."
    "Pilot" "Yes mam!"
    
    "The pursuit continues, until they are cornered"
    love "Aim for their engines"
    
    "The enemy ship jerks, and your team misses their target. Unfortunately, for them, it hits their hull, doing massive damage."
    love "Hail them again, demand surrender."
    love "You! Private!"
    "Private" "Me?"
    love "Yes, you. Get medics on standby."
    "Private" "But... no one is hurt. Everyone is fine..."
    jacobs "Not for us you idiot! Them! We want them in custody, not dead!"
    "Private" "R-... right!"
    "The private runs off"
    
    jacobs "Captain! Look!"
    "The bandit craft shuts down, and motion can be seen inside through some windows"
    
    love "Do you think their comms are down?"
    jacobs "Possibly..."
    love "Keep an eye out for a signal. A white flag..."
    
    "In an instant, two small pods jetison from the craft"
    
    love "Wha-- -what?!"
    love "After them!"
    jacobs "But, what about the ship? There could be other casualties..."
    love "I didn't... you're... you're right. Get the med team suited up. They're going in"
    
    "No one is found aboard the craft. Everyone jettisoned, and they got away. Once again"
    
    jacobs "This will at least stop them from plundering trade ships"
    
    love "Yes. For a while at least..."
    
    "After a few more days, with no contact, love docks back onto the surface for her scheduled leave"
    
    love "I can't believe I let them get away..."
    max "Let who get away?"
    love "Max! I- I didn't think I'd see you again!"
    max "Heh, why? What's up?"
    love "I never got to thank you... you and your brother..."
    gray "You can thank me with icecream!"
    "Everyone laughs. You all get icecream"
    "Grayson eventually heads home, and you and Max share a nice evening in the park"
    
    love "I forgot to ask, what happened to your arm?"
    "Max's arm is in a cast"
    max "Ohh, this? Ha, well... it's a... work hazard I presume? ha ha"
    
    "Love suddenly has flashbacks to the shot down ship, and the ejected pods"
    love "What... what exactly do you do?"
    max "This and that, I'm a bit of a freelancer, I suppose."
    love "Ohh... and... your arm..."
    love "Was there... a fight?"
    max "Eh, you could say so"
    "silence"
    max "But I have to admit, it was pretty one sided. You can imagine who lost."
    "silence"
    
    love "Max....."
    max "Yeah?"
    love "What... What exact--"
    "Love is cut off by someone yelling in the distance"
    gray "Max! Max! He's back! And he's causing a scene!"
    max "Not this guy again. Umm... this won't take long."
    "Max gets up"
    max "You, uhh, you're welcome to come with. It won't take long, I promise"
    "You agree"
    
    "Max grabs your hand and leads you out of the park, back into town"
    max "Sorry, we gotta get there quick"
    "You nearly trip over the un-even sidewalk. You're definitely in the rundown part of town"
    
    max "Hey, asshole!"
    "Biker" "Wha? Who you calling asshole?"
    max "You, asshole! I told you, you're not welcome here anymore! We've given you enough chances, now scram!"
    "Biker" "Look. Max. Listen..."
    max "No, you look here. We've given you more than enough chances, and you've blown them all."
    "Biker" "But, Max..."
    max "Don't 'But Max' me. It ain't happening. Get. Out."
    "The biker looks down, defeated."
    "He slowly gets back onto his bike."
    max "Hey"
    "Biker" "Hmm?"
    max "Next week. One more chance. ONE."
    "The biker smiles, starts up his bike, and heads off"
    
    love "Um... what was that about?"
    max "Him? He's just got a few too many knocks to his head. Can't quite tell right from wrong anymore."
    
    "You follow Max into the shop, and..."
    "You follow Max into the shop, and..."
    "You're overwhelmed with the most delicious smells! Spices! Herbs! Cheeses!"
    
    gray "Today's 'Italy day'!"
    max "It's 'Italian Day'. Today we're serving Italian food, specifically, spaghetti and garlic bread"
    
    love "It's... a homeless shelter?"
    max "Yeah. It's also a Kitchen. I've been volunteering here lately. It's not much, but it's good work!"
    gray "The place was about to shut down before Max and I stepped in!"
    max "Ha, no way!"
    max "Mrs. Patricia would have found a way to keep the place running"
    
    love "Ohh! So your arm...? I'm still a little confused..."
    max "I mean, you saw the guy out there? Let's just say not everyone is noble and kind-hearted as Grayson here"
    gray "I'm going to grow up to be a policeman!"
    max "Yeah... I'm still working on convincing him out of that one"
    "Everyone laughs"
    
    "Love spends the next few days with Max, volunteering at the shelter, and growing ever closer."
    "They spend the last evening of her leave in the park, watching the sun set"
    
    love "I can't believe this is my last day"
    max "So what? You'll be back after another week. And I'll be here, waiting for you"
    love "Waiting for me?"
    max "I mean--"
    "He blushes"
    max "I mean me and Grayson, and Mrs. Patricia... you've helped out so much these past couple days"
    "You blush"
    
    love "Well. I better be off."
    max "Yeah. I'll... I'll miss you."
    "There is a silence"
    gray "Are you two going to kiss now?"
    max "Grayson! What are you doing here!"
    gray "Mrs Patricia said I should keep an eye on you two, and make sure you don't get into trouble"
    max "Get out of here! I'll be home soon."
    "Grayson runs off"
    love "I guess..."
    max "I guess this is goodbye, I'll..."
    love "I'll see you in a week"
    "You two hold hands. And..."
    "He lets go..."
    "And you walk away..."
    
    "You think about him that night, for the rest of the night."
    love "When I get back... I'll tell him. I'll tell him how I feel"
    
    "Days pass. Nothing interesting happens."
    
    jacobs "Um... hmmm... this is odd"
    love "What is it?"
    jacobs "This ship doesn't match it's signature. It's off..."
    love "So? Maybe the signal-"
    jacobs "There's more... it looks like this ship was recently stolen from a Junkyard."
    love "So... Just to be clear: Someone stole a hunk-of-junk, and doesn't want anyone to know?"
    jacobs "Yup"
    love "Let's flag him down!"
    
    "As your crew approaches, the ship notices, and takes off"
    love "Are you serious?"
    jacobs "It's clearly a stolen vehicle, the punishment for that is pretty stiff. What did you expect?"
    love "The place is extremely crowded."
    love "Last time... someone got in the way..."
    jacobs "I know"
    love "Innocents died"
    jacobs "I know"
    love "..."
    love "...let him go."
    "The crew is silent"
    jacobs "I agree, captain."
    
    "Cook" "You did the right thing, why risk it?"
    love "Thanks. I... I believe we did"
    "Love spends the rest of the day thinking about the incident. Was it the right thing?"
    
    jacobs "We've got a problem"
    love "What's up?"
    jacobs "We've got an emergency report, a transport ship has been robbed."
    love "You heard him pilot, let's go!"
    "Pilot" "Yes m'am"
    jacobs "There's... there's more Love"
    love "What is it?"
    jacobs "There was a struggle, one casualty."
    love "These asshole bandits.. They just don't care..."
    jacobs "There's... still more Love"
    love "Seriously?? What else could it be?"
    jacobs "According to the co-pilot, the vehicle matches the description of the one we let go earlier"
    "There's a silence"
    jacobs "Are you... Are you okay Love?"
    love "Yes. Let's... Let's just do our job, okay?"
    
    "You and your crew head to the scene, and patrol the area for a few hours"
    jacobs "I got him. Right here"
    love "What?"
    jacobs "Here, on the edge of our scanners, a signal change. I saw it with my own eyes. The logs confirm."
    jacobs "This vehicle is illegally changing signals."
    love "Let's go"
    "You approach the signal, and the ship quickly comes into view"
    
    love "That's it. That's him."
    jacobs "What do we do? We haven't been noticed."
    love "Send a message. Tell him to surrender."
    jacobs "... Yes mam."
    jacobs "..."
    jacobs "Sent."
    "Everyone waits in silence"
    jacobs "The ship, it's engines are starting up. I believe it's trying to flee"
    love "Open fire."
    jacobs "Roger."
    "Your crew gives off a warning shot, but causes severe damage to the ship"
    love "What happened!?!"
    jacobs "Umm... It.. It looks like the ship has no shields."
    love "What the hell??? It's illegal to fly a ship without even basic shielding! What if a piece of space junk hit him?"
    jacobs "Love, the ship was stolen from a Junk yard... maybe the thief didn't know..."
    love "Get a medical team out there right away! We need to make sure he's alive, and in custody. NOW!"
    
    "Everyone scatters, as love listens closely to their transmissions"
    
    "Medical Team Member" "This looks bad."
    "Medical Team Member" "..."
    "Medical Team Member" "The external hatch is stuck. Electronics are down. Life support is down."
    "Medical Team Member" "I'm torching the door."
    "Medical Team Member" "No de-pressurization."
    "Medical Team Member" "..."
    "Medical Team Member" "One body."
    "Medical Team Member" "No suit."
    "Medical Team Member" "..."
    "Medical Team Member" "That's it. One casualty, and no survivors."
    
    "Love is visibly pissed"
    jacobs "To be fair... the transport... he... I mean, he did..."
    love "That's no excuse. We made SO many mistakes today. I can't even begin to think about all this"
    
    "Several days pass without incident"
    "There is a judicial review of the events that unfolded"
    "The crew is not found accountable for either death"
    "'There's no way anyone could have known'"
    
    "You and Jacobs take an early leave, heading back to the planet"
    "You head directly to the shelter"
    "All you can think about is what you've done... and Max."
    "Would he forgive you? Could he?"
    "You slow down... take your time."
    "You're just delaying the inevitable"
    "But, eventually, you get there. The shelter."
    gray "Love! You're back early!"
    love "Yes, I am"
    "She forces a smile"
    love "Where's max?"
    gray "He still isn't back. Mrs. Patricia sent him out on some errand"
    love "Right..."
    
    "A few hours pass, when Love finally spots Mrs. Patricia"
    
    love "Patty! Hey!"
    patty "Hello Love! You're back early!"
    love "Yes, I couldn't wait. Where's Max? I haven't seem him all day."
    "The smile leaves Mrs. Patricia's face"
    patty "Um, come with me Love"
    "You follow her into the next room, as Grayson gets up"
    patty "No, you stay right there Mr."
    patty "Us adults need a moment to talk."
    gray "Aw man..."
    "He sits back down"
    
    love "What... what is it Mrs. Patricia?"
    patty "Love. I'm sorry. I'm so sorry. There was an accident."
    love "An, accident?"
    patty "... did, Max ever tell you what he did?"
    love "Yes... he volunteers here. He feeds the homeless. He helped save the place"
    "Mrs. Patricia's eyes begin to well up as she smiles"
    patty "Yes. Yes he did..."
    patty "Did he ever tell you how he saved the place?"
    love "No."
    patty "Love. I... I don't know what to say."
    love "What... What happened?"
    patty "He. Max. He was a good kid. His heart was always in the right place."
    patty "We had no money. We had no way to buy food. We could barely afford rent as it is."
    patty "I could have just gotten another job, but..."
    patty "All those hungry people that come everyday... the starving poor..."
    patty "Some of them are children..."
    patty "Then, one day, Max kicks in the door..."
    "Mrs. Patricia smiles"
    patty "I'll never forget, he said something like..."
    patty "'M'am, I heard you're in need of a hero'"
    patty "You have to understand,"
    patty "I had no idea who he was at the time, and he just barges in like that.."
    "She laughs"
    patty "I attacked him with a frying pan. I thought he was just some hooligan, looking to start a fight"
    "She's quiet for a moment"
    patty "He had a whole truckload of food for us. Various grains and cereals, vegetables, meats..."
    patty "It was the most generous donation we've ever received."
    "Both of you smile"
    patty "But, it didn't last forever. We had enough money to afford the place, but ran low on food again."
    patty "A couple days pass, and Miracle Max pops by again with a full truck and a broken arm!"
    patty "He needed a cast, but all he cared about was getting the truck unloaded before the food spoiled!"
    "Mrs. Patricia sighs"
    patty "He told me... He told me what happened"
    patty "Who he really was"
    "You see a shadow move beneath the door"
    patty "Grayson...!"
    "The door slowly opens"
    gray "Yes, mam?"
    patty "Were you evesdropping again?"
    gray "Yes mam..."
    "He looks down"
    "Mrs. Patricia lets out a long sigh"
    patty "Come here boy,"
    patty "We're talking about your brother"
    "Grayson's face lights up"
    gray "We are!"
    "He excitedly runs over"
    gray "Love, did he ever tell you the time he fought off over a hundred pirates! All on his own!"
    patty "Not now, Grayson"
    patty "Come, sit down next to Love"
    "Grayson excitedly pulls up a chair and sits"
    patty "So, as I was fixing his broken arm..."
    gray "Ohh! I know this one! Robinhood!"
    patty "Yeah... that's what he said. That's what he told me. That the food was stolen."
    patty "He'd steal the food from transport ships, and brought it here"
    "There is a silence in the room"
    gray "But it was for the greater good! To help people! Brother wouldn't hurt nobody!"
    patty "That's right. Your brother wouldn't harm a fly. Because of him... we were able to help so many people..."
    patty "I... so..."
    patty "So, we're low on food again. He insisted on getting more."
    patty "I told him no, it's dangerous, there's got to be a better way"
    patty "But he insisted"
    patty "He said, 'One more'..."
    patty "'One more, then we'll find a better way'"
    "She begins to tear up again"
    patty "I... I don't know exactly what happened."
    patty "But, based on the news... I guess there was a struggle."
    patty "Someone got killed."
    patty "Because of that... They... the officers... they killed him."
    "The room is silent"
    patty "I'm... I'm sorry Grayson. I'm sorry I couldn't tell you before."
    "Mrs. Patricia begins crying"
    patty "Your brother. Max. Max is dead."
    pause
    "The end."
    return